apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: ernestmr/mk-auth
    context: auth
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - infra/k8s/auth-depl.yaml
