apiVersion: v1
kind: PersistentVolume
metadata:
  name: ticket-mo-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/appdata/mongo/tickets
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ticket-mo-data-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
