name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{secret.DIGITALOCEAN_ACCESS_TOKEN}}

      - run: |
          # Build new image
          cd auth && docker build -t $DOCKER_USERNAME/mk-auth . \
          # Push to docker hub
          && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD \
          && docker push $DOCKER_USERNAME/mk-auth
