name: deploy-manifest

on:
  push:
    branches: 
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: action/checkout@v2
     - uses: digitalocean/action-doct@v2
       with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
     - run: doctl kubernetes cluster kubeconfig save ticketing
     - run: |
        # Update deployment
        kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod


     
     
      
       
      
